// Static manifest mapping OSIS book IDs to bundled XML assets for Expo/React Native
// We use static require() so Metro can bundle these files as assets

export const ARASVD_BOOK_ASSETS = {
  Gen: require('./gen.xml'),
  Exod: require('./exod.xml'),
  Lev: require('./lev.xml'),
  Num: require('./num.xml'),
  Deut: require('./deut.xml'),
  Josh: require('./josh.xml'),
  Judg: require('./judg.xml'),
  Ruth: require('./ruth.xml'),
  '1Sam': require('./1sam.xml'),
  '2Sam': require('./2sam.xml'),
  '1Kgs': require('./1kgs.xml'),
  '2Kgs': require('./2kgs.xml'),
  '2Chr': require('./2chr.xml'),
  Ezra: require('./ezra.xml'),
  Neh: require('./neh.xml'),
  Esth: require('./esth.xml'),
  Job: require('./job.xml'),
  Ps: require('./ps.xml'),
  Prov: require('./prov.xml'),
  Eccl: require('./eccl.xml'),
  Song: require('./song.xml'),
  Isa: require('./isa.xml'),
  Jer: require('./jer.xml'),
  Lam: require('./lam.xml'),
  Ezek: require('./ezek.xml'),
  Dan: require('./dan.xml'),
  Hos: require('./hos.xml'),
  Joel: require('./joel.xml'),
  Amos: require('./amos.xml'),
  Obad: require('./obad.xml'),
  Jonah: require('./jonah.xml'),
  Mic: require('./mic.xml'),
  Nah: require('./nah.xml'),
  Hab: require('./hab.xml'),
  Zeph: require('./zeph.xml'),
  Hag: require('./hag.xml'),
  Zech: require('./zech.xml'),
  Mal: require('./mal.xml'),
  Matt: require('./matt.xml'),
  Mark: require('./mark.xml'),
  Luke: require('./luke.xml'),
  John: require('./john.xml'),
  Acts: require('./acts.xml'),
  Rom: require('./rom.xml'),
  '1Cor': require('./1cor.xml'),
  '2Cor': require('./2cor.xml'),
  Gal: require('./gal.xml'),
  Eph: require('./eph.xml'),
  Phil: require('./phil.xml'),
  Col: require('./col.xml'),
  '1Thess': require('./1thess.xml'),
  '2Thess': require('./2thess.xml'),
  '1Tim': require('./1tim.xml'),
  '2Tim': require('./2tim.xml'),
  Titus: require('./titus.xml'),
  Phlm: require('./phlm.xml'),
  Heb: require('./heb.xml'),
  Jas: require('./jas.xml'),
  '1Pet': require('./1pet.xml'),
  '2Pet': require('./2pet.xml'),
  '1John': require('./1john.xml'),
  '2John': require('./2john.xml'),
  '3John': require('./3john.xml'),
  Jude: require('./jude.xml'),
  Rev: require('./rev.xml'),
};

export const ARASVD_ORDER = [
  'Gen','Exod','Lev','Num','Deut','Josh','Judg','Ruth','1Sam','2Sam','1Kgs','2Kgs','1Chr','2Chr',
  'Ezra','Neh','Esth','Job','Ps','Prov','Eccl','Song','Isa','Jer','Lam','Ezek','Dan','Hos','Joel',
  'Amos','Obad','Jonah','Mic','Nah','Hab','Zeph','Hag','Zech','Mal',
  'Matt','Mark','Luke','John','Acts','Rom','1Cor','2Cor','Gal','Eph','Phil','Col','1Thess','2Thess',
  '1Tim','2Tim','Titus','Phlm','Heb','Jas','1Pet','2Pet','1John','2John','3John','Jude','Rev'
];
