// Arabic AVD (with tashkeel) per-book asset manifest for Expo/React Native
// We map OSIS IDs to statically-required XML files located under ./books/<number>.xml

export const ARAVD_BOOK_ASSETS = {
  Gen: require('./books/1.xml'),
  Exod: require('./books/2.xml'),
  Lev: require('./books/3.xml'),
  Num: require('./books/4.xml'),
  Deut: require('./books/5.xml'),
  Josh: require('./books/6.xml'),
  Judg: require('./books/7.xml'),
  Ruth: require('./books/8.xml'),
  '1Sam': require('./books/9.xml'),
  '2Sam': require('./books/10.xml'),
  '1Kgs': require('./books/11.xml'),
  '2Kgs': require('./books/12.xml'),
  '1Chr': require('./books/13.xml'),
  '2Chr': require('./books/14.xml'),
  Ezra: require('./books/15.xml'),
  Neh: require('./books/16.xml'),
  Esth: require('./books/17.xml'),
  Job: require('./books/18.xml'),
  Ps: require('./books/19.xml'),
  Prov: require('./books/20.xml'),
  Eccl: require('./books/21.xml'),
  Song: require('./books/22.xml'),
  Isa: require('./books/23.xml'),
  Jer: require('./books/24.xml'),
  Lam: require('./books/25.xml'),
  Ezek: require('./books/26.xml'),
  Dan: require('./books/27.xml'),
  Hos: require('./books/28.xml'),
  Joel: require('./books/29.xml'),
  Amos: require('./books/30.xml'),
  Obad: require('./books/31.xml'),
  Jonah: require('./books/32.xml'),
  Mic: require('./books/33.xml'),
  Nah: require('./books/34.xml'),
  Hab: require('./books/35.xml'),
  Zeph: require('./books/36.xml'),
  Hag: require('./books/37.xml'),
  Zech: require('./books/38.xml'),
  Mal: require('./books/39.xml'),
  Matt: require('./books/40.xml'),
  Mark: require('./books/41.xml'),
  Luke: require('./books/42.xml'),
  John: require('./books/43.xml'),
  Acts: require('./books/44.xml'),
  Rom: require('./books/45.xml'),
  '1Cor': require('./books/46.xml'),
  '2Cor': require('./books/47.xml'),
  Gal: require('./books/48.xml'),
  Eph: require('./books/49.xml'),
  Phil: require('./books/50.xml'),
  Col: require('./books/51.xml'),
  '1Thess': require('./books/52.xml'),
  '2Thess': require('./books/53.xml'),
  '1Tim': require('./books/54.xml'),
  '2Tim': require('./books/55.xml'),
  Titus: require('./books/56.xml'),
  Phlm: require('./books/57.xml'),
  Heb: require('./books/58.xml'),
  Jas: require('./books/59.xml'),
  '1Pet': require('./books/60.xml'),
  '2Pet': require('./books/61.xml'),
  '1John': require('./books/62.xml'),
  '2John': require('./books/63.xml'),
  '3John': require('./books/64.xml'),
  Jude: require('./books/65.xml'),
  Rev: require('./books/66.xml'),
};

export const ARAVD_ORDER = [
  'Gen','Exod','Lev','Num','Deut','Josh','Judg','Ruth','1Sam','2Sam','1Kgs','2Kgs','1Chr','2Chr',
  'Ezra','Neh','Esth','Job','Ps','Prov','Eccl','Song','Isa','Jer','Lam','Ezek','Dan','Hos','Joel',
  'Amos','Obad','Jonah','Mic','Nah','Hab','Zeph','Hag','Zech','Mal',
  'Matt','Mark','Luke','John','Acts','Rom','1Cor','2Cor','Gal','Eph','Phil','Col','1Thess','2Thess',
  '1Tim','2Tim','Titus','Phlm','Heb','Jas','1Pet','2Pet','1John','2John','3John','Jude','Rev'
];
